import type { Metadata } from "next";
import ReactDOM from "react-dom";
import "./globals.css";
import { cookies } from "next/headers";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	let themeCookieValue;
	if (process.env.NODE_ENV === "production") {
		const cookieStore = await cookies();
		const themeCookie = cookieStore.get("theme");
		themeCookieValue = themeCookie?.value;
		if (themeCookie?.value === "blue") {
			ReactDOM.preload(
				`/_next/static/css/${process.env.TAILWIND_THEME_blue}.css`,
				{ as: "style" },
			);
		} else {
			ReactDOM.preload(
				`/_next/static/css/${process.env.TAILWIND_THEME_red}.css`,
				{ as: "style" },
			);
		}
	}
	return (
		<html lang="en">
			<head>
				<link
					rel="stylesheet"
					href={
						themeCookieValue === "blue"
							? `/_next/static/css/${process.env.TAILWIND_THEME_blue}.css`
							: `/_next/static/css/${process.env.TAILWIND_THEME_red}.css`
					}
				/>
			</head>
			<body className={`antialiased`}>{children}</body>
		</html>
	);
}
