import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const themes = {
	red: {
		styles: [
			`
    --primary-color: red;
    --secondary-color: orange;
    `,
		],
	},
	blue: {
		styles: [
			`
      --primary-color: blue;
      --secondary-color: teal;
      `,
		],
	},
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>{children}</body>
			<style>{`:root{${themes.blue.styles}}`}</style>
		</html>
	);
}
